### PR TITLE
Issue 21 branch source customization

### PR DESCRIPTION
**Pull request by robvanderleek**

### CODE REVIEW

**Comment by robvanderleek** [comment]
Fixes #21

**Comment by ilyasmohamed** [comment]
Hi @robvanderleek 
Did you want me to review this PR?

**Comment by robvanderleek** [comment]
Hi @ilyasmohamed 
Yes, please review this PR 😄 
I've implemented:

- Configure source branch for label
- Configure branch prefix
- Use simple variable substitution in branch prefix

You can install the CIB staging app on a repo to test these features: https://github.com/apps/create-issue-branch-staging

See the `README.md` for some documentation.

Also feel free to review/modify the implementation. Let me know about any questions you might have on running the code/tests/etc. (the documentation for that is non-existing but I do try to keep things as standard as possible)

**Comment by ilyasmohamed** [comment]
@robvanderleek I'll make sure to get this done on the weekend as I'll be free then. 👍

**Comment by robvanderleek** [comment]
That would be great! 😄

**Comment by ilyasmohamed** [comment]
This is excellent. Tested out using staging app and it works perfectly. Haven't tested many variable substitution but the one I tried worked. Great job 👍

**Comment by robvanderleek** [comment]
fixes #21

**Pull request merged**
